### ISSUE TITLE
user missing in "New finds by" on Friends page

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#989] opened 2019-02-21 09:06 UTC
User "Děda Fana" is missing in the "New finds by:" section.

![obrazek](https://user-images.githubusercontent.com/9153595/53154457-1e003f80-35bb-11e9-91fa-1ef78ec7529e.png)

I guess the reason might be the non-ASCII character in his username - "ě".

Here's the source code of the affected part of the page:

[source_code_part.zip](https://github.com/2Abendsegler/GClh/files/2888454/source_code_part.zip)

GC little helper II 0.9.16, FF 65.0.1 x64, Win 7 x64.

**Comment by Ruko2010** [comment] 2019-02-21 09:34
Hmm...I have no idea how to reproduce this, because i have not a single friend in my list with special chars in his name. @2Abendsegler do you have such a friend in your list?

**Comment by PontiacCZ** [comment] 2019-02-21 09:45
That's why I attached the HTML source code. I thought it could be sufficient for you to somehow reproduce the issue on your computer.

I may also give you the the Friends page HTML source before GClh modified it, if you're interested.

**Comment by Ruko2010** [comment] 2019-02-21 11:25
I'm not sure the html code will help. But we find a way to reproduce the issue for sure ;)

**Comment by Ruko2010** [comment] 2019-02-21 11:27
btw, a Big Thank to you @PontiacCZ for Reporting so much! We always try to improve GClh, but without feedback it is hard to do so! So again. Thank You ❤️

**Comment by PontiacCZ** [comment] 2019-02-21 11:55
No problem, you're welcome. GClh is a great tool and it's worth a little effort from us, users. :-)

**Comment by 2Abendsegler** [comment] 2019-02-21 20:39
It seems to be not the special sign ...

![grafik](https://user-images.githubusercontent.com/22332216/53199794-4bcb9f80-3620-11e9-8ee5-6a017ae55f6e.png)

---
I think it is the space. But user with space are not allowed today. And I have not such a friend with space.

**Comment by 2Abendsegler** [comment] 2019-02-21 20:52
If I look to the console the name loos like: DědaFana
In the html of PontiacCZ look like: DÄ›da Fana
Perhaps my ě is not the same ě like PontiacsCZ.

@PontiacCZ can you please look to the console to the name and post the presentation of the name here.

**Comment by PontiacCZ** [comment] 2019-02-22 07:39
@2Abendsegler : my HTML file is saved in UTF-8 and there is "Děda Fana" in there... But I forced the file to reload in CP1250 now and indeed I see "DÄ›da Fana", just like you. :-)

My "ě" - unicode number U+11B - https://unicode-table.com/en/011B/ . I think we are talking about the same character.

Please specifiy what you mean by console and I will be happy to provide the requested information.

**Comment by 2Abendsegler** [comment] 2019-02-22 15:16
@PontiacCZ, sorry. 
To the console:
1. Go to friendspage https://www.geocaching.com/my/myfriends.aspx
2. Go with your mouse over the user name, click right mouse and choose "examine element" (oder similar)
3. The console opens and shows the user. 

All together looks like 
![grafik](https://user-images.githubusercontent.com/22332216/53251266-8daa2380-36bc-11e9-988e-406b536481a1.png)

If the user looks like Děda Fana, I would type that it is the space which create the problem and not the ě.
If it is so, Ruko2010 have you a user with space in the name?

**Comment by PontiacCZ** [comment] 2019-02-22 19:03
Ah, I see. Here it is:

![obrazek](https://user-images.githubusercontent.com/9153595/53264781-c0fcaa80-36dc-11e9-8660-9c0ab03343da.png)

**Comment by Ruko2010** [comment] 2019-02-22 21:21
> If it is so, Ruko2010 have you a user with space in the name?

Yes I have, and that is not the problem:
![image](https://user-images.githubusercontent.com/2239440/53271939-2efe9d00-36f0-11e9-82fd-29bcda2fe3d3.png)

**Comment by Ruko2010** [comment] 2019-02-25 08:15
So, I made some more tests. I renamed our test account to have such a special char in it (please note, I could not enter a username with a space in it, maybe GS prohibited this in the near past). 
Then a made a log entry and went to the friends page. All worked fine. 
<img width="940" alt="bildschirmfoto 2019-02-25 um 09 11 22" src="https://user-images.githubusercontent.com/2239440/53323138-9594de00-38dd-11e9-98ad-ec52c6f7cfc6.png">

This Bug is not reproduceable. And if we can't reproduce it, we can't fix it 😔

**Comment by Ruko2010** [comment] 2019-02-25 08:15
I'm really out of ideas. @2Abendsegler have you any idea left?

**Comment by Ruko2010** [comment] 2019-02-25 12:08
@PontiacCZ is "Děda Fana" familiar with GClh and the Bug/Problem? Maybe he could add me as a friend for testing purpose (My Username on geocaching.com is also "Ruko2010")?

**Comment by PontiacCZ** [comment] 2019-02-25 12:28
No, he is not, but that's a good idea, I'll instruct him to add you temporarily into Friends.

**Comment by Ruko2010** [comment] 2019-02-26 07:33
Hi @PontiacCZ 
Děda Fana added me as a friend and I tested it. Sorry that I have to say, but it is working for me!
![image](https://user-images.githubusercontent.com/2239440/53394590-0d2b4180-39a0-11e9-9afd-88e4a2b68283.png).

I tested it with Chrome and FF to exclude a browser issue. Can you do me a favor and install this script and see if your friend shows up?
https://github.com/Ruko2010/GClh/raw/test/gc_little_helper_II.user.js

What it will do:
1. Add some testoutput to the console. 
2. Set the last_found count for Děda Fana to fixed 1300.

After installing the script, please visit the friends page and open the console (Extras => Web-Developer => Web Console). There should be many output. Just copy it and past it here. **It is important, that you get the console-output from the first page vistit!!**

If you can now see Děda Fana, just install the original GClh and see if he is still there:
https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js

**Comment by PontiacCZ** [comment] 2019-02-26 07:41
I don't know what to say but it works for me now as well, still with the original GClh II ! :-o

![image](https://user-images.githubusercontent.com/9153595/53395405-0b627d80-39a2-11e9-9893-5a6b06ead1b7.png)

Do you still need me to install the special version of GClh?

**Comment by Ruko2010** [comment] 2019-02-26 07:43
No, if it works, it's fine. I'll close this issue.

**Closed by Ruko2010** 2019-02-26 07:43 UTC
Labels: bug
