### ISSUE TITLE
Icons below "Logged Visits" are not displayed

### ISSUE THREAD

**Issue by UlliH1** [2Abendsegler/GClh#2070] opened 2022-03-07 18:10 UTC
### Describe the bug

Already some versions of GClh ago my browser does not display the line with icons "Found", "Not found" etc below "Logged visits" and above "View all logs" anymore.

### To Reproduce

1. Go to first log entry
![Missing icons](https://user-images.githubusercontent.com/101134830/157092568-bf863c35-375b-4596-9b0a-78b9e29455eb.jpg)
.

### Expected behavior

The icons should be displayed.

### OS

Windows

### Browser

Firefox

### GClh Version

0.11.12

**Comment by capoaira** [comment] 2022-03-07 18:19
Thank you for reporting the bug.
We are working on a solution.

I close this Issue, because it is a duplicate of #2044

**Closed by capoaira** 2022-03-07 18:19 UTC
Labels: bug, tag: duplicate

**Comment by UlliH1** [comment] 2022-03-07 18:31
Thank you for the very quick response! I'm looking forward to a solution! Thanks in advance!
