### ISSUE TITLE
Last Log Option does not work

### ISSUE THREAD

**Issue by struppi1963** [2Abendsegler/GClh#2449] opened 2023-11-12 11:08 UTC
### Describe the bug

Due to changes to the log page on the geocaching website, the option to use the last log for a new log no longer works.

### OS

Windows

### Browser

Firefox

### GClh Version

0.14.6

**Comment by capoaira** [comment] 2023-11-12 13:18
Thank you for reporting the bug.

GS has redesigned the whole Log Form. We are currently working to implement all features from the old log forms.

Duplicate of #2424

**Closed by capoaira** 2023-11-12 13:18 UTC
Labels: bug, tag: duplicate
