### ISSUE TITLE
Myfinds.gpx "Add to queue" button not working

### ISSUE THREAD

**Issue by Lineflyer** [2Abendsegler/GClh#2064] opened 2022-02-28 19:10 UTC
### Describe the bug

I am not 100% sure about this problem (as once I was able to add "My finds" to the queue I can no longer test it).

Basically I noticed, that nothing happend when trying to generate a myfinds.gpx and it only worked once I deactivated Tampermonkey.

### To Reproduce

- Go to https://www.geocaching.com/pocket/ with activated Tampermonkey and GCLH script
- Click on the "Add to queue" button to generate a myfinds.gpx
- Nothing happens

### Expected behavior

Message "Your .... has been scheduled to run" from the website

### OS

Windows

### Browser

Chrome

### GClh Version

0.11.12

**Comment by capoaira** [comment] 2022-02-28 19:17
Thank you for reporting the bug.
We will work on it as soon as we find time for this project again.

This Issue is related or a duplicate of #2028

**Comment by Lineflyer** [comment] 2022-02-28 19:57
@capoaira Could you reproduce, because I was not 100% sure its caused by GCLH or any other buggy thing on gc.com

**Comment by capoaira** [comment] 2022-02-28 20:03
Yes I can reproduce.
Without the gclh the button works

**Comment by capoaira** [comment] 2022-03-08 08:56
Bug is fixed in #2028

**Closed by capoaira** 2022-03-08 08:56 UTC
Labels: bug, tag: duplicate
