### ISSUE TITLE
[Cache Listing] External Links warning

### ISSUE THREAD

**Issue by Pprime1** [2Abendsegler/GClh#2069] opened 2022-03-07 12:30 UTC
### Is your feature request related to a problem? Please describe

When clicking on a link on a  cache page that goes to a site page not on geocaching.com (for example Project-GC checker), an annoying popup appears to warn me that I am doing exactly that. Can that popup be removed?

### Describe the solution you'd like

no popup

**Comment by capoaira** [comment] 2022-03-07 19:06
I think this is a duplicate of #2053 

What other pages are affected besides the cache listing?

**Comment by 2Abendsegler** [comment] 2022-03-07 21:16
> I think this is a duplicate of #2053

👍

> @2Abendsegler What other pages are affected besides the cache listing?

😓 I have changed the headline in #2053.

**Closed** 2022-03-07 22:52 UTC
Labels: tag: duplicate, enhancement
