### ISSUE TITLE
New log form: Strange reload ca. 1 second after opening the log page

### ISSUE THREAD

**Issue by dcjkfgdjhd** [2Abendsegler/GClh#2541] opened 2023-12-24 14:30 UTC
### Describe the bug

When I enter the new log page, and it seems to be completely loaded, ca. 1 second later it reloads again. This is incredibly annoying when trying to quickly log many caches.

Before the reload, the default log type choice has NOT yet been selected. After the reload, it HAS been selected. So I am guessing that it is the log type selecting that is causing the reload.

Other GClh features, such as log template, appear BEFORE the reload, so they do NOT seem to be the cause.

### OS

Windows

### Browser

Firefox

### GClh Version

0.15.3

**Comment by capoaira** [comment] 2023-12-24 16:57
Hello,
your right, to set the default logtype we have to reload the page. This it not beautiful but the only way we found. 
To avoid these reloading you just have to disable (set to `- select type of log -`) the default logtype in the GClh config.

Since this is the expected behaviour, I'll close this issue 

Merry Christmas 🎅

**Closed** 2023-12-24 16:57 UTC
Labels: bug, tag: invalid

**Comment by 2Abendsegler** [comment] 2024-01-08 21:27
@dcjkfgdjhd
Hi, with the next version, a reload is no longer necessary. @DieBatzen found a great solution (#2544).

**Comment by dcjkfgdjhd** [comment] 2024-01-09 08:44
Super, vielen Dank. Und gleich wieder was neues gelernt (React)!
