### ISSUE TITLE
GClh Warning: Image not available - for essential image

### ISSUE THREAD

**Issue by epnl** [2Abendsegler/GClh#1222] opened 2020-01-14 09:53 UTC
obsolete

**Comment by 2Abendsegler** [comment] 2020-01-14 11:08
Can you please give me some more information, maybe also a link. At the moment I don't know where the problem is.

**Comment by 2Abendsegler** [comment] 2020-01-14 11:16
... if there is no longer a problem, you can close the issue with the button "Close issue".

**Comment by 2Abendsegler** [comment] 2020-01-15 06:47
I think the issue is obsolet.

**Closed by 2Abendsegler** 2020-01-15 06:47 UTC
